openapi: 3.0.1
info:
  title: Hello API
  version: 1.0.0
paths:
  /hello:
    get:
      summary: Retrieve a hello message
      responses:
        '200':
          description: A successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hello, World!
      tags:
        - Hello